version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postech_phase1
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - '5432'

volumes:
  dbdata: